server:
  port: 9010
# -- Default spring configuration

spring:
  application:
    name: api-gateway-service

# -- Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:9000/eureka/}
# -- Zuul
zuul:
  routes:
    user-service2:
      path: /user/**
      service-id: user-server
    user-service3:
      path: /test/**
      service-id: test-server