server:
  port: 9002


# -- Default spring configuration

spring:
  application:
    name: user-server

# -- Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:9000/eureka/}

## -- Zuul
#zuul:
#  routes:
#    user-service:
#      path: /user/**
#      service-id: USER-SERVICE